version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/wallet-core
    schedule:
      interval: weekly
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: /packages/tx-builder
    schedule:
      interval: weekly
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: /packages/chain-rpc
    schedule:
      interval: weekly
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: /packages/portfolio
    schedule:
      interval: weekly
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: /apps/onboarding
    schedule:
      interval: weekly
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
